[ncatbot]
# 核心设置
allow_plugins = true
auto_reload = true

# 屏蔽目录
ignored_directories = [
    "test",
    "tests",
    "__pycache__"
]

# 日志设置
[log]
level = "INFO"
file = "logs/bot.log"
max_size = 10  # MB
backup_count = 5

# 插件设置
[plugins]
auto_load = true
paths = ["plugins"]

# 安全设置
[security]
super_users = [12345678]  # 超级用户ID列表