[ncatbot]
# 核心设置
allow_plugins = true
auto_reload = true

# 插件设置
[plugins]
auto_load = true
paths = ["plugins"]  # 指定插件目录，只有此目录下的模块会被加载为插件

# 以下目录不会被加载为插件（记录性质，无实际作用）
# - test
# - tests
# - __pycache__

# 日志设置
[log]
level = "INFO"
file = "logs/bot.log"
max_size = 10  # MB
backup_count = 5

# 安全设置
[security]
super_users = [12345678]  # 超级用户ID列表